Repository Lucy-Arti/Arti-Server, pull requests merged in 2023-11, with the labels that each got.

#32 [feat] point shop, 주문 기능 구현
  .DS_Store
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/lucy/arti/ArtiApplication.java
  src/main/java/com/lucy/arti/comment/controller/CommentController.java
  src/main/java/com/lucy/arti/comment/domain/Answer.java
  src/main/java/com/lucy/arti/comment/domain/Comment.java
  src/main/java/com/lucy/arti/comment/dto/AnswerDto.java
  src/main/java/com/lucy/arti/comment/dto/CommentDto.java
  src/main/java/com/lucy/arti/comment/dto/MemberDto.java
  src/main/java/com/lucy/arti/comment/repository/AnswerRepository.java
  src/main/java/com/lucy/arti/comment/repository/CommentRepository.java
  src/main/java/com/lucy/arti/comment/service/CommentService.java
  src/main/java/com/lucy/arti/member/domain/Member.java
  src/main/java/com/lucy/arti/member/repository/MemberRepository.java
  src/main/java/com/lucy/arti/member/service/MemberService.java
  src/main/java/com/lucy/arti/point/controller/GlobalExceptionHandler.java
  src/main/java/com/lucy/arti/point/controller/PointController.java
  src/main/java/com/lucy/arti/point/domain/Point.java
  src/main/java/com/lucy/arti/point/dto/InstagramRequest.java
  src/main/java/com/lucy/arti/point/dto/PointDto.java
  src/main/java/com/lucy/arti/point/dto/PointInfoDto.java
  src/main/java/com/lucy/arti/point/dto/PointValuesResponse.java
  src/main/java/com/lucy/arti/point/repository/PointRepository.java
  src/main/java/com/lucy/arti/point/service/PointService.java
  src/main/java/com/lucy/arti/point/service/S3Uploader.java
  src/main/java/com/lucy/arti/pointDelivery/controller/AuthenticationHelper.java
  src/main/java/com/lucy/arti/pointDelivery/controller/DeliveryController.java
  src/main/java/com/lucy/arti/pointDelivery/domain/Delivery.java
  src/main/java/com/lucy/arti/pointDelivery/dto/DeliveryDto.java
  src/main/java/com/lucy/arti/pointDelivery/dto/DeliveryRequest.java
  src/main/java/com/lucy/arti/pointDelivery/repository/DeliveryRepository.java
  src/main/java/com/lucy/arti/pointDelivery/service/DeliveryService.java
  src/main/java/com/lucy/arti/pointHistory/controller/PointHistoryController.java
  src/main/java/com/lucy/arti/pointHistory/domain/PointHistory.java
  src/main/java/com/lucy/arti/pointHistory/dto/PointHistoryDto.java
  src/main/java/com/lucy/arti/pointHistory/repository/PointHistoryRepository.java
  src/main/java/com/lucy/arti/pointHistory/service/PointHistoryService.java
  src/main/java/com/lucy/arti/pointShop/controller/ShopController.java
  src/main/java/com/lucy/arti/pointShop/domain/ShopCategory.java
  src/main/java/com/lucy/arti/pointShop/domain/ShopItem.java
  src/main/java/com/lucy/arti/pointShop/dto/ShopDto.java
  src/main/java/com/lucy/arti/pointShop/repository/ShopRepository.java
  src/main/java/com/lucy/arti/pointShop/service/NotFoundException.java
  src/main/java/com/lucy/arti/pointShop/service/ShopService.java
  src/main/java/com/lucy/arti/vote/service/VoteService.java
  src/main/resources/application.properties
Labels: Feature

#50 [기능] 어드민 - 옷, 디자이너
  src/main/java/com/lucy/arti/clothes/domain/Clothes.java
  src/main/java/com/lucy/arti/clothes/dto/ClothesDetailResponseDto.java
  src/main/java/com/lucy/arti/comment/repository/CommentRepository.java
  src/main/java/com/lucy/arti/designer/controller/DesignerController.java
  src/main/java/com/lucy/arti/designer/domain/Designer.java
  src/main/java/com/lucy/arti/designer/dto/DesignerDetailResponseDto.java
  src/main/java/com/lucy/arti/designer/repository/DesignerRepository.java
  src/main/java/com/lucy/arti/designer/service/DesignerService.java
Labels: Feature

#52 [fix] imgTime 변수 db매핑 수정
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/com/lucy/arti/point/domain/Point.java
Labels: Bug

#54 [어드민] 포인트, 딜리버리 어드민 기능 추가
  .gitignore
  src/main/java/com/lucy/arti/global/exception/ErrorCode.java
  src/main/java/com/lucy/arti/member/repository/MemberRepository.java
  src/main/java/com/lucy/arti/point/controller/PointController.java
  src/main/java/com/lucy/arti/point/domain/Point.java
  src/main/java/com/lucy/arti/point/dto/PointAdminDto.java
  src/main/java/com/lucy/arti/point/dto/PointCreateDto.java
  src/main/java/com/lucy/arti/point/repository/PointRepository.java
  src/main/java/com/lucy/arti/point/service/PointService.java
  src/main/java/com/lucy/arti/pointDelivery/controller/DeliveryController.java
  src/main/java/com/lucy/arti/pointDelivery/domain/Delivery.java
  src/main/java/com/lucy/arti/pointDelivery/dto/DeliveryDto.java
  src/main/java/com/lucy/arti/pointDelivery/dto/DeliveryUpdateDto.java
  src/main/java/com/lucy/arti/pointDelivery/repository/DeliveryRepository.java
  src/main/java/com/lucy/arti/pointDelivery/service/DeliveryService.java
  src/main/java/com/lucy/arti/pointHistory/domain/PointHistory.java
Labels: Feature

#59 [FIX] 어드민 페이지 디자이너 생성 로직 변경
  .gitignore
  src/main/java/com/lucy/arti/designer/controller/DesignerController.java
  src/main/java/com/lucy/arti/designer/domain/Designer.java
  src/main/java/com/lucy/arti/designer/dto/DesignerPostDto.java
  src/main/java/com/lucy/arti/designer/repository/DesignerRepositoryCustom.java
  src/main/java/com/lucy/arti/designer/repository/DesignerRepositoryImpl.java
  src/main/java/com/lucy/arti/designer/service/DesignerService.java
Labels: Bug, Feature
